travis:
  secure:
    BINSTAR_TOKEN: dgGT17OeXIggYekR5C1D42fmYB3sY2/cgvy2SxDqGWMLH2myzMV9gDHXDKyaeaH3NkTJWb3N6ww576YVNd9O5BgRF9iZIwb6pA+X1gM3LQP1OzSMR3q4ev+rHjEXw+vojWyWjLP7YHvBwGTIDQ/dkxKtPlArDfMI4J8E2dstat7hHeh/AIA6XJqkwh70p4OTpBOfDKs/aUxEFpVjRubYHjByd4EpmPFKEwb2XPBT/gWX7O2c1NaumLV7OYOIK0OpfBWhAmFyCqsUQN6ypA4500aFATE5OrmfSzAGHIZ8flqB+mLbEcuUBeKRPmwqtpYFO+UPF1XMz0o/OkrWzTLUHA1pEsrLwY7yATRzOfL3HSVXIHm50ysLZAlSm6c8vseb/+aRLyZjz+ZsDLDXmjGr2pwPE3WsZMiHuDYlwx6VMl557ChhpdtVkgP+ocJCc4l406cszRAKlRVGi0gn1v/FnlGtpy1DzFMP+firGr6UYMqJyb9mg3SMC1x6tpKDi0C8AKaN1igvBVBz3J9vNvE/zLstGDRVYSktpM0RhzfmYTCEYFlZo+ZGmXI7X3SIVjSq95w13pzPjn9/KIGPqp+8mlFSYnV5Tbl3FPx47xJ6FgZxYomh2fwkce76DKhitv0nK+I1NZCerqwt5JnSzgeuqiOA9r8pZRqqwOKKhleQUQE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
